# Generated by Django 3.0.7 on 2020-07-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WFreq',
            fields=[
                ('wordid', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=45)),
                ('frequency', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'wfreq',
            },
        ),
    ]
